"""added a phonenumber

Revision ID: 92c87f8c1d9c
Revises: 
Create Date: 2025-10-25 18:35:06.963633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c87f8c1d9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_customer_id'), table_name='customer')
    op.drop_table('customer')
    op.add_column('users', sa.Column('phonenumber', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phonenumber')
    op.create_table('customer',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('customer_pkey'))
    )
    op.create_index(op.f('ix_customer_customer_id'), 'customer', ['customer_id'], unique=False)
    # ### end Alembic commands ###
